Repository ARMmbed/connectedhomeip, pull requests merged in 2021-04, with the labels that each got.

#96 Add Lock-app example for mbed platform
  .github/workflows/examples-mbed.yaml
  .vscode/launch.json
  .vscode/tasks.json
  config/mbed/mbedtls/chip_mbedtls_config.h
  examples/lock-app/mbed/.gitignore
  examples/lock-app/mbed/CMakeLists.txt
  examples/lock-app/mbed/config.in
  examples/lock-app/mbed/main/AppTask.cpp
  examples/lock-app/mbed/main/BoltLockManager.cpp
  examples/lock-app/mbed/main/ZclCallbacks.cpp
  examples/lock-app/mbed/main/include/AppEvent.h
  examples/lock-app/mbed/main/include/AppTask.h
  examples/lock-app/mbed/main/include/BoltLockManager.h
  examples/lock-app/mbed/main/include/CHIPProjectConfig.h
  examples/lock-app/mbed/main/main.cpp
  examples/lock-app/mbed/mbed-os.lib
  examples/lock-app/mbed/mbed_app.json
  examples/lock-app/mbed/wifi-ism43362.lib
  examples/platform/mbed/util/LEDWidget.cpp
  examples/platform/mbed/util/include/LEDWidget.h
  examples/shell/mbed/CMakeLists.txt
  scripts/examples/mbed_example.sh
  scripts/examples/mbed_example_utils.sh
  src/platform/BUILD.gn
  src/platform/mbed/BLEManagerImpl.cpp
  src/platform/mbed/arch.c
Labels: Example

#159 Fix getaddrinfo(), result buffer allocation and set hinst IP type
  src/platform/mbed/net/src/net_dns.cpp
Labels: bug

#160 Openocd platform support
  .devcontainer/Dockerfile
  .github/workflows/examples-mbed.yaml
  .vscode/launch.json
  .vscode/tasks.json
  config/mbed/CMakeLists.txt
  config/mbed/scripts/DISCO_L475VG_IOT01A.tcl
  scripts/examples/mbed_example.sh
  scripts/examples/mbed_example_utils.sh
Labels: cleanup, improvement
